name: Java CI with Maven

# Controls when the workflow will run
on:
  # Run on pushes to the main branch
  push:
    branches: [ "main" ]
  # Run on pull requests to the main branch
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    # Run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java Development Kit (JDK) version 11
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Build the project and run the tests with Maven
      - name: Build and Test with Maven
        run: mvn -B test
