name: Build and Deploy HTML

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the main branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This single job is called "deploy"
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Validates all HTML files in the repository for errors
      - name: Validate HTML
        uses: validator/validator # <-- This line is now fixed
        with:
          files: ./*.html # Validates all .html files in the root directory

      # 3. Sets up the GitHub Pages environment for deployment
      # - name: Setup Pages
      #   uses: actions/configure-pages@v5

      # # 4. Uploads your site's files as a build artifact
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     # Upload the entire repository
      #     path: '.'

      # # 5. Deploys the artifact to GitHub Pages
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4
